// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  lib

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( FileUploadRequest ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* FileUploadRequest ) UnmarshalJSON([]byte) error { return nil }
func ( FileUploadRequest ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* FileUploadRequest ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_FileUploadRequest *FileUploadRequest

func ( FilesRequest ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* FilesRequest ) UnmarshalJSON([]byte) error { return nil }
func ( FilesRequest ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* FilesRequest ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_FilesRequest *FilesRequest

func ( FilesResponse ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* FilesResponse ) UnmarshalJSON([]byte) error { return nil }
func ( FilesResponse ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* FilesResponse ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_FilesResponse *FilesResponse

func ( User ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* User ) UnmarshalJSON([]byte) error { return nil }
func ( User ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* User ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_User *User

func ( UserRequest ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* UserRequest ) UnmarshalJSON([]byte) error { return nil }
func ( UserRequest ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* UserRequest ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_UserRequest *UserRequest
