// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  lib

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( AddCategoryRequest ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* AddCategoryRequest ) UnmarshalJSON([]byte) error { return nil }
func ( AddCategoryRequest ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* AddCategoryRequest ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_AddCategoryRequest *AddCategoryRequest

func ( CategoriesList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* CategoriesList ) UnmarshalJSON([]byte) error { return nil }
func ( CategoriesList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* CategoriesList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_CategoriesList *CategoriesList

func ( FileRequest ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* FileRequest ) UnmarshalJSON([]byte) error { return nil }
func ( FileRequest ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* FileRequest ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_FileRequest *FileRequest

func ( FileUploadRequest ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* FileUploadRequest ) UnmarshalJSON([]byte) error { return nil }
func ( FileUploadRequest ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* FileUploadRequest ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_FileUploadRequest *FileUploadRequest

func ( User ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* User ) UnmarshalJSON([]byte) error { return nil }
func ( User ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* User ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_User *User

func ( UserRequest ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* UserRequest ) UnmarshalJSON([]byte) error { return nil }
func ( UserRequest ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* UserRequest ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_UserRequest *UserRequest
